apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-wallet-api-deployment
  labels:
    app: simple-wallet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-wallet-api
  template:
    metadata:
      labels:
        app: simple-wallet-api
    spec:
      containers:
        - name: simple-wallet-api
          image: 421720294106.dkr.ecr.eu-central-1.amazonaws.com/wallet-system:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
