apiVersion: v1
kind: Service
metadata:
  name: simple-wallet-service
spec:
  selector:
    app: simple-wallet-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
